version: "3.9"
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_POR:27017
    volumes:
      - six-cities_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_ROOT_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DB_ROOT_USER:$DB_PASSWORD@$DB_HOST:$PORT
    depends_on:
      - db

volumes:
  six-cities_data:

